name: GitHub Child workflow
on: [workflow_call]
jobs:
  download-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: download-artifact
        uses: actions/download-artifact@v3
        with:
          name: child-artifact
      - run: cat child-workflow-artifact.txt
