name: GitHub Child workflow
on: [workflow_call]
jobs:
  download-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: download-artifact
        uses: actions/download-artifact@v3
        with:
          name: my-artifact
      - run: cat build-artifact.txt
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: upload-artifact
        uses: actions/upload-artifact@v3
        with:
          name: child-artifact
          path: child-workflow-artifact.txt
