name: GitHub Dispatched workflow
on: [workflow_dispatch]
jobs:
  download-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: download-artifact
        run: echo "My Workflow was Dispatched"
